Hello-world project
sheldonwafula/Hello-World pull request #1
Opened 2023-02-14 19:03 UTC by sheldonwafula

In this pull request:
I have created a heading.
I have styled my heading using CSS.
 I have corrected all linter errors.

2023-02-14 19:21 UTC, Tadesse-Alemayehu requested changes
### Hi @sheldonwafula 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)

## Highlights
 - [ ]  Correct GitHub Flow  ✅
 - [ ]  Good commit history  ✅
 - [ ]  Good PR title/description  ✅
 - [ ]  All linters passed  ✅
 
## Required Changes ♻️
- [ ] Please consider removing non-important contents from your readme, The template is designed by Microverse for us all to use to document our projects professionally and has it filled with content related to each project we may be working on. currently, I can see you have not removed the guiding contents  which start with `>` and `directions set by Microverser`

_Check the comments under the review._

## Optional suggestions
- [Optinal] I would suggest you separately commit your changes and use a descriptive name for your commit message alongside other good practices. Currently, you have a single commit `add html file`, but in a single commit, you have modified more than 9 files. Assume comments as a save point and you have to have descriptive message if you ever wonna go back. 
 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-14 19:21 UTC, Tadesse-Alemayehu commented on README.md
> +
- [ ] Notice the link for your MIT file is broken, Please make sure to add the MIT license file and update its content in regard to your name and project. Also replace the `[YOUR NAME]` part with your name, and `[APP TYPE]` with your app type.

2023-02-14 19:21 UTC, Tadesse-Alemayehu commented on README.md
> +
- [ ] Please notice the section in your readme which start with `>` are directions/guidelines from microverse to help you understand what to write in that section and should not be part of your readme file. Please consider removing this and all the like contents from the readme file.

2023-02-15 05:16 UTC, NahnahAJ requested changes
Hi @sheldonwafula , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.
<img src="https://media3.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

 ## Highlights
- [ ] Good use of Github flow :heavy_check_mark: 
- [ ] No linter errors :heavy_check_mark: 
- [ ] Good PR title and Description :heavy_check_mark:  

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 05:16 UTC, NahnahAJ commented on .gitignore
> +node_modules
- [ OPTIONAL ] As part of the [Project Requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md), you were asked to  add 

> A test.md file with the text "This file should be ignored by git".
> Make sure that the last file is actually ignored by git and is not present in your GitHub repository.
But I noticed you didn't fulfill this requirement. Please note that this project was to help you learn how to make use of some of these files in this case the `.gitignore` so you can make good use of it in your future projects :100: 
- Even though this is an optional comment, I will suggest you do it to serve as practice for you :+1: 
- [ ] You can read more about how `.gitignore` works [here](https://www.bmc.com/blogs/gitignore/).

2023-02-15 05:16 UTC, NahnahAJ commented on README.md
> +> Describe how a new developer could make use of your project.
- [ ] As the previous reviewer suggested before,  Please remove this line since it is also part of the directions/guidelines from microverse to help you understand what to write in that section :+1:

2023-02-15 06:13 UTC, christianbiring1 approved these changes
Hi @sheldonwafula , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 

## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary`
## Optional suggestions
- [ ] As suggested previously, kindly make sure you add a `test.md` which will be ignored by git.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 06:28 UTC, merged